# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json
controllers:
    resource: routing.controllers

# Ruta del login JWT
api_login:
    path: /api/login
    methods: [POST]